apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: lc-graph
  labels:
    {{- include "lc-graph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
=======
  name: {{ include "lc-graph.fullname" . }}
  labels:
    {{- include "lc-graph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
>>>>>>> 252cfa0 (add lc graph helm chart)
      targetPort: http
      protocol: TCP
      name: http
  selector:
<<<<<<< HEAD
    {{- include "lc-graph.labels" . | nindent 4 }}
=======
    {{- include "lc-graph.selectorLabels" . | nindent 4 }}
>>>>>>> 252cfa0 (add lc graph helm chart)
