apiVersion: v1
kind: Service
metadata:
  name: lc-graph
  labels:
    {{- include "lc-graph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lc-graph.labels" . | nindent 4 }}
