---
# Source: lc-graph-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lc-graph-write
  labels:
    app: lc-graph-write
    env: fullaccess
spec:
  type: NodePort
  ports:
    - port: 8043
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lc-graph-write
    env: fullaccess
---
# Source: lc-graph-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-graph-write
  labels:
    app: lc-graph-write
    env: fullaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lc-graph-write
      env: fullaccess
  template:
    metadata:
      labels:
        app: lc-graph-write
        env: fullaccess
    spec:
      containers:
        - name: lc-graph-server
          securityContext:
            null
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports: 
            - name: http
              containerPort: 8043
              protocol: TCP
          env:
            - name: R_POSTGRES_HOST
              value: {{ quote .Values.app.postgresql.read.host }}
            - name: R_POSTGRES_DATABASE
              value: {{ quote .Values.app.postgresql.read.database }}
            - name: R_POSTGRES_USERNAME
              value: {{ quote .Values.app.postgresql.read.username }}
            - name: R_POSTGRES_PASSWORD
              value: {{ quote .Values.app.postgresql.read.password }}
            - name: R_POSTGRES_PORT
              value: {{ quote .Values.app.postgresql.read.port }}   
            - name: W_POSTGRES_ENABLED
              value: "true"
            - name: W_POSTGRES_HOST
              value: {{ quote .Values.app.postgresql.write.host }}    
            - name: W_POSTGRES_DATABASE
              value: {{ quote .Values.app.postgresql.write.database }}
            - name: W_POSTGRES_USERNAME
              value: {{ quote .Values.app.postgresql.write.username }}
            - name: W_POSTGRES_PASSWORD
              value: {{ quote .Values.app.postgresql.write.password }}
            - name: W_POSTGRES_PORT
              value: {{ quote .Values.app.postgresql.write.port }}
          livenessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
            initialDelaySeconds: 180
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
            initialDelaySeconds: 180
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          # volumeMounts:
          # - name: config
          #   mountPath: /app/config
          #   readOnly: true
      volumes:
        - name: config
          configMap: 
            name: full-access-configmap
