app:
  env: fullaccess
  replicaCount: 1
  image:
    lc-graph:
      repository: fptblockchainlabbot/lc-graph
      tag: 0.1.0
      pullPolicy: IfNotPresent
  containerPort: 8043

  service:
    type: NodePort
    port: 8043

  # You need to provide some config file. For example, just copy `example_config.toml`
  config: "config.toml"

  # Optional
  ingress:
    enabled: true
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - host: lc-graph.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  # We don't need this, but you might want to set this to something

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  postgresql:
    read:
      database: lcgraph
      username: lcgraph
      password: lcgraph
      port: 5432
    write:
      enabled: false
      database: lcgraph
      username: lcgraph
      password: lcgraph
      port: 5432
