app:
  env: fullaccess
  replicaCount: 1
  image: 
    repository: noobmdev/lc-grapqh
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 3000

  service:
    type: NodePort
    port: 8043

  # Optional
  ingress:
    enabled: true
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - host: lc-graph.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  # We don't need this, but you might want to set this to something

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  postgresql:
    read:
      host: 1.23.24.256
      database: postgres
      username: postgres
      password: postgres
      port: 5432
    write:
      enabled: false
      host: 1.23.24.256
      database: postgres
      username: postgres
      password: postgres
      port: 5432
