<<<<<<< HEAD
app:
  replicaCount: 1
  env: fullaccess
  image:
    lc-graph: 
      repository: https://github.com/FPT-Blockchain-Lab/lc-graph-server
      tag: main
      pullPolicy: IfNotPresent
    lc:
      repository: local
      tag: v4.1.3-beta
      pullPolicy: IfNotPresent
  containerPort: 8043

  service:
    type: NodePort
    port: 8043

  # You need to provide some config file. For example, just copy `example_config.toml`
  config: "config.toml"

  # Optional
  ingress:
    enabled: true
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - host: lc-graph.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  # We don't need this, but you might want to set this to something

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  postgresql:
    read:
      database: lcgraph
      username: lcgraph
      password: lcgraph
      port: 5432
    write: {}

  subgraph:
    postgrest_connection_url: "jdbc:postgresql://1.54.89.227:5432/testnet_lc_graph"
    ethereum_jsonrpc_endpoint: goquorum-node-rpc
=======
replicaCount: 1
image:
  lc-graph: 
    repository: https://github.com/FPT-Blockchain-Lab/lc-graph-server
    tag: main
    pullPolicy: IfNotPresent
  lc:
    repository: local
    tag: v4.1.3-beta
    pullPolicy: IfNotPresent
containerPort: 8043

service:
  type: NodePort
  port: 8043

# You need to provide some config file. For example, just copy `example_config.toml`
config: "config.toml"

# Optional
ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: lc-graph.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# We don't need this, but you might want to set this to something

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 1Gi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

postgresql:
  read:
    database: lcgraph
    username: lcgraph
    password: lcgraph
    port: 5432
  write:
    database: lcgraph
    username: lcgraph
    password: lcgraph
    port: 5432

subgraph:
  postgrest_connection_url: "jdbc:postgresql://1.54.89.227:5432/testnet_lc_graph"
  ipfs_endpoint: ipfs-1
  ethereum_jsonrpc_endpoint: goquorum-node-rpc
>>>>>>> 252cfa0 (add lc graph helm chart)
