apiVersion: v1
version: 0.1.4
appVersion: latest
name: goquorum-genesis
description: Quorum Genesis generator with Helm chart in Kubernetes
keywords:
  - ethereum
  - quorum
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://github.com/FPT-Blockchain-Lab
sources:
  - https://github.com/FPT-Blockchain-Lab/helm-charts/charts/goquorum-genesis
maintainers:
  - name: Truong Ma Phi 
    email: trmaphi@gmail.com

